project:
  type: website
  output-dir: docs

website:
#  favicon: imgs/favicon.png
  title: "Mundy, K."
  navbar:
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - resources.qmd
      - misc.qmd
#  announcement: 
#    icon: info-circle
#    dismissable: true
#    content: "**Alert** - this is some information that you should pay attention to"
#    type: secondary
#    position: below-navbar
#  page-footer: |
  

format:
  html:
    theme: 
      dark: [sandstone, theme-dark.scss]
      light: [sandstone, theme-light.scss]
    css: styles.css
    toc: true


editor: source

