---
title: "Misc."
---
Miscellaneous links and lists of things that are relevant to me.

## Baking Recipes (with Notes)


- [Butter Pecan Cookies](https://sallysbakingaddiction.com/butter-pecan-cookies/)
    - Honestly not sure I ever remember the cornstarch for this one, but it turns out good either way.
    - Vanilla extract is meant to be measured with the heart.
- [Key Lime Pie](https://www.allrecipes.com/recipe/15880/key-lime-pie-vii/)
    - Not sure what kind of super-oven they're baking their pies in, but I've found that it needs ~20 minutes in the oven before it starts to bubble.
    - The base recipe asks for 3 cups of condensed milk, but cans often come in 14 fl oz. I just use two entire cans of fat-free condensed milk and keep the other ingredients at the specified amount (this often means I have enough for two 9-in pie crusts or one 12-in with some raw batter left to eat).
    - Goes well with [homemade whipped cream](https://sallysbakingaddiction.com/homemade-whipped-cream/).

- [Lemon Curd Thumbprint Cookies](https://pastryandbeyond.com/ginger-thumbprint-cookies-lemon-curd/)
    - Can substitute the lemon curd for your preferred jam or fruit preserve (I'm a big fan of raspberry).
    - I always use 2-3 times more cinnamon to give the cookie a little more flavor.
    - Make sure you have enough space to store these! Even after they fully cool, the curd tends to be sticky, so they're not very stackable.
- [Sugar Cookies (Cutout)](https://www.browneyedbaker.com/go-pens-with-all-occasion-sugar-cookies/)
    - If there aren't allergy concerns, I recommend adding a bit of almond extract.
    - I always chill the dough for at least 20-30 minutes (but that's also because I'm usually ready for a break after mixing the dough by hand).
    - Use powdered sugar instead of flour when you're rolling them out!
    - Good base cookie for [royal icing](https://preppykitchen.com/royal-icing/).
